// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const discoverCandidates = `-- name: DiscoverCandidates :many
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at
FROM personas p
JOIN participants pa ON pa.id = p.participant_id
LEFT JOIN passes ps
       ON ps.from_persona_id = $1
      AND ps.to_persona_id = p.id
WHERE pa.game_date = $2
  AND p.id <> $1
  AND p.id <> ALL ($3::uuid[])
  AND COALESCE(ps.pass_count, 0) < 3
  AND NOT EXISTS (
      SELECT 1 FROM likes l
      WHERE l.from_persona_id = $1
        AND l.to_persona_id = p.id
  )
  AND NOT EXISTS (
      SELECT 1 FROM matches m
      WHERE (m.persona_low_id = $1 AND m.persona_high_id = p.id)
         OR (m.persona_low_id = p.id AND m.persona_high_id = $1)
  )
ORDER BY p.exposure_count ASC, random()
LIMIT $4
`

type DiscoverCandidatesParams struct {
	SelfID     uuid.UUID
	GameDate   time.Time
	ExcludeIds []uuid.UUID
	LimitCount int32
}

// Candidate selection for the discover screen. Every rule lives here so the
// exclusions cannot drift apart from each other:
//
//	not self / today's game day / not already liked / not already matched /
//	pass_count < 3 / not in the frontend's cooldown list.
//
// Priority is the least exposed persona first, then random among equals.
// Returning a batch must never change exposure_count.
func (q *Queries) DiscoverCandidates(ctx context.Context, arg DiscoverCandidatesParams) ([]Persona, error) {
	rows, err := q.db.Query(ctx, discoverCandidates,
		arg.SelfID,
		arg.GameDate,
		arg.ExcludeIds,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Persona{}
	for rows.Next() {
		var i Persona
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Age,
			&i.Gender,
			&i.HeightCm,
			&i.Education,
			&i.Occupation,
			&i.AnnualIncome,
			&i.Name,
			&i.Hobby,
			&i.Bio,
			&i.ExposureCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
