// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discover.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const discoverCandidates = `-- name: DiscoverCandidates :many
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at, p.bonus_likes, p.profile_reward_claimed, p.match_reward_count
FROM personas p
JOIN participants pa ON pa.id = p.participant_id
LEFT JOIN passes ps
       ON ps.from_persona_id = $1
      AND ps.to_persona_id = p.id
WHERE pa.game_date = $2
  AND p.id <> $1
  AND p.id <> ALL ($3::uuid[])
  AND COALESCE(ps.pass_count, 0) < 3
  AND NOT EXISTS (
      SELECT 1 FROM likes l
      WHERE l.from_persona_id = $1
        AND l.to_persona_id = p.id
  )
  AND NOT EXISTS (
      SELECT 1 FROM matches m
      WHERE (m.persona_low_id = $1 AND m.persona_high_id = p.id)
         OR (m.persona_low_id = p.id AND m.persona_high_id = $1)
  )
ORDER BY p.exposure_count ASC, random()
LIMIT $4
`

type DiscoverCandidatesParams struct {
	SelfID     uuid.UUID
	GameDate   time.Time
	ExcludeIds []uuid.UUID
	LimitCount int32
}

// Discover 画面の候補選択。除外条件が散らばって食い違わないよう、ルールは
// すべてここに集約している:
//
//	自分以外 / 当日のゲーム日 / Like済みでない / Match済みでない /
//	pass_count < 3 / フロントのクールダウン一覧に含まれない。
//
// 優先度は exposure_count が少ない順、同数ならランダム。
// バッチを返すだけでは exposure_count を絶対に変えない。
func (q *Queries) DiscoverCandidates(ctx context.Context, arg DiscoverCandidatesParams) ([]Persona, error) {
	rows, err := q.db.Query(ctx, discoverCandidates,
		arg.SelfID,
		arg.GameDate,
		arg.ExcludeIds,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Persona{}
	for rows.Next() {
		var i Persona
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Age,
			&i.Gender,
			&i.HeightCm,
			&i.Education,
			&i.Occupation,
			&i.AnnualIncome,
			&i.Name,
			&i.Hobby,
			&i.Bio,
			&i.ExposureCount,
			&i.CreatedAt,
			&i.PhotoUpdatedAt,
			&i.BonusLikes,
			&i.ProfileRewardClaimed,
			&i.MatchRewardCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
