// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLikesReceived = `-- name: CountLikesReceived :one
SELECT COUNT(*) FROM likes WHERE to_persona_id = $1
`

func (q *Queries) CountLikesReceived(ctx context.Context, toPersonaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesReceived, toPersonaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLikesSent = `-- name: CountLikesSent :one
SELECT COUNT(*) FROM likes WHERE from_persona_id = $1
`

// 当日消費した Like 数。前日の Persona は二度と行動できないため likes の行は
// 常に当日の Persona を指す。したがって日付での絞り込みは不要。
func (q *Queries) CountLikesSent(ctx context.Context, fromPersonaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLikesSent, fromPersonaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasLikesReceivedSince = `-- name: HasLikesReceivedSince :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE to_persona_id = $1
      AND created_at > COALESCE($2::timestamptz, 'epoch'::timestamptz)
) AS has_unseen
`

type HasLikesReceivedSinceParams struct {
	PersonaID uuid.UUID
	Since     *time.Time
}

func (q *Queries) HasLikesReceivedSince(ctx context.Context, arg HasLikesReceivedSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLikesReceivedSince, arg.PersonaID, arg.Since)
	var has_unseen bool
	err := row.Scan(&has_unseen)
	return has_unseen, err
}

const insertLike = `-- name: InsertLike :one
INSERT INTO likes (id, from_persona_id, to_persona_id)
VALUES ($1, $2, $3)
ON CONFLICT (from_persona_id, to_persona_id) DO NOTHING
RETURNING id
`

type InsertLikeParams struct {
	ID            uuid.UUID
	FromPersonaID uuid.UUID
	ToPersonaID   uuid.UUID
}

func (q *Queries) InsertLike(ctx context.Context, arg InsertLikeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertLike, arg.ID, arg.FromPersonaID, arg.ToPersonaID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const likeExists = `-- name: LikeExists :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE from_persona_id = $1
      AND to_persona_id = $2
) AS like_exists
`

type LikeExistsParams struct {
	FromPersonaID uuid.UUID
	ToPersonaID   uuid.UUID
}

func (q *Queries) LikeExists(ctx context.Context, arg LikeExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, likeExists, arg.FromPersonaID, arg.ToPersonaID)
	var like_exists bool
	err := row.Scan(&like_exists)
	return like_exists, err
}
