// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listMatches = `-- name: ListMatches :many
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at
FROM matches m
JOIN personas p ON p.id = CASE
    WHEN m.persona_low_id = $1 THEN m.persona_high_id
    ELSE m.persona_low_id
END
WHERE m.persona_low_id = $1
   OR m.persona_high_id = $1
ORDER BY m.created_at DESC, m.id DESC
`

// Only the counterpart persona of each match, newest first.
func (q *Queries) ListMatches(ctx context.Context, personaID uuid.UUID) ([]Persona, error) {
	rows, err := q.db.Query(ctx, listMatches, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Persona{}
	for rows.Next() {
		var i Persona
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Age,
			&i.Gender,
			&i.HeightCm,
			&i.Education,
			&i.Occupation,
			&i.AnnualIncome,
			&i.Name,
			&i.Hobby,
			&i.Bio,
			&i.ExposureCount,
			&i.CreatedAt,
			&i.PhotoUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedLikes = `-- name: ListReceivedLikes :many
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at
FROM likes l
JOIN personas p ON p.id = l.from_persona_id
WHERE l.to_persona_id = $1
ORDER BY l.created_at DESC, l.id DESC
`

// Personas who liked the current persona, newest first. No timestamps and no
// sender budget information are exposed.
func (q *Queries) ListReceivedLikes(ctx context.Context, personaID uuid.UUID) ([]Persona, error) {
	rows, err := q.db.Query(ctx, listReceivedLikes, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Persona{}
	for rows.Next() {
		var i Persona
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Age,
			&i.Gender,
			&i.HeightCm,
			&i.Education,
			&i.Occupation,
			&i.AnnualIncome,
			&i.Name,
			&i.Hobby,
			&i.Bio,
			&i.ExposureCount,
			&i.CreatedAt,
			&i.PhotoUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentLikes = `-- name: ListSentLikes :many
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at, EXISTS (
    SELECT 1 FROM matches m
    WHERE (m.persona_low_id = $1 AND m.persona_high_id = p.id)
       OR (m.persona_low_id = p.id AND m.persona_high_id = $1)
) AS matched
FROM likes l
JOIN personas p ON p.id = l.to_persona_id
WHERE l.from_persona_id = $1
ORDER BY l.created_at DESC, l.id DESC
`

type ListSentLikesRow struct {
	ID             uuid.UUID
	ParticipantID  uuid.UUID
	Age            int16
	Gender         string
	HeightCm       int16
	Education      string
	Occupation     string
	AnnualIncome   int32
	Name           *string
	Hobby          *string
	Bio            *string
	ExposureCount  int32
	CreatedAt      time.Time
	PhotoUpdatedAt *time.Time
	Matched        bool
}

// The day's like allocation history. Matched targets stay in the list and are
// flagged so the screen can show a MATCH badge.
func (q *Queries) ListSentLikes(ctx context.Context, personaID uuid.UUID) ([]ListSentLikesRow, error) {
	rows, err := q.db.Query(ctx, listSentLikes, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSentLikesRow{}
	for rows.Next() {
		var i ListSentLikesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Age,
			&i.Gender,
			&i.HeightCm,
			&i.Education,
			&i.Occupation,
			&i.AnnualIncome,
			&i.Name,
			&i.Hobby,
			&i.Bio,
			&i.ExposureCount,
			&i.CreatedAt,
			&i.PhotoUpdatedAt,
			&i.Matched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
