// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const listMatches = `-- name: ListMatches :many
SELECT
    m.id AS match_id,
    p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at, p.profile_reward_claimed, p.match_reward_count, p.like_balance, p.like_recovery_anchor_at,
    EXISTS (
        SELECT 1 FROM match_children c WHERE c.match_id = m.id
    ) AS child_generated
FROM matches m
JOIN personas p ON p.id = CASE
    WHEN m.persona_low_id = $1 THEN m.persona_high_id
    ELSE m.persona_low_id
END
WHERE m.persona_low_id = $1
   OR m.persona_high_id = $1
ORDER BY m.created_at DESC, m.id DESC
`

type ListMatchesRow struct {
	MatchID        uuid.UUID
	Persona        Persona
	ChildGenerated bool
}

// 各 Match の相手 Persona を新しい順に返す。
//
// match_id を添えるのは、一覧のカードから Match 詳細を開けるようにするため。
// child_generated は子ガチャを引いたかどうかで、一覧では「👶 子あり」の
// 目印と、詳細を開いたときに演出を出すかどうかの判断に使う。子の中身そのものは
// 一覧には出さない。
func (q *Queries) ListMatches(ctx context.Context, personaID uuid.UUID) ([]ListMatchesRow, error) {
	rows, err := q.db.Query(ctx, listMatches, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesRow{}
	for rows.Next() {
		var i ListMatchesRow
		if err := rows.Scan(
			&i.MatchID,
			&i.Persona.ID,
			&i.Persona.ParticipantID,
			&i.Persona.Age,
			&i.Persona.Gender,
			&i.Persona.HeightCm,
			&i.Persona.Education,
			&i.Persona.Occupation,
			&i.Persona.AnnualIncome,
			&i.Persona.Name,
			&i.Persona.Hobby,
			&i.Persona.Bio,
			&i.Persona.ExposureCount,
			&i.Persona.CreatedAt,
			&i.Persona.PhotoUpdatedAt,
			&i.Persona.ProfileRewardClaimed,
			&i.Persona.MatchRewardCount,
			&i.Persona.LikeBalance,
			&i.Persona.LikeRecoveryAnchorAt,
			&i.ChildGenerated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReceivedLikes = `-- name: ListReceivedLikes :many
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at, p.profile_reward_claimed, p.match_reward_count, p.like_balance, p.like_recovery_anchor_at
FROM likes l
JOIN personas p ON p.id = l.from_persona_id
WHERE l.to_persona_id = $1
ORDER BY l.created_at DESC, l.id DESC
`

// 自分に Like を送った Persona を新しい順に返す。時刻も送信者の Like 残数も
// 一切公開しない。
func (q *Queries) ListReceivedLikes(ctx context.Context, personaID uuid.UUID) ([]Persona, error) {
	rows, err := q.db.Query(ctx, listReceivedLikes, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Persona{}
	for rows.Next() {
		var i Persona
		if err := rows.Scan(
			&i.ID,
			&i.ParticipantID,
			&i.Age,
			&i.Gender,
			&i.HeightCm,
			&i.Education,
			&i.Occupation,
			&i.AnnualIncome,
			&i.Name,
			&i.Hobby,
			&i.Bio,
			&i.ExposureCount,
			&i.CreatedAt,
			&i.PhotoUpdatedAt,
			&i.ProfileRewardClaimed,
			&i.MatchRewardCount,
			&i.LikeBalance,
			&i.LikeRecoveryAnchorAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentLikes = `-- name: ListSentLikes :many
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at, p.profile_reward_claimed, p.match_reward_count, p.like_balance, p.like_recovery_anchor_at, EXISTS (
    SELECT 1 FROM matches m
    WHERE (m.persona_low_id = $1 AND m.persona_high_id = p.id)
       OR (m.persona_low_id = p.id AND m.persona_high_id = $1)
) AS matched
FROM likes l
JOIN personas p ON p.id = l.to_persona_id
WHERE l.from_persona_id = $1
ORDER BY l.created_at DESC, l.id DESC
`

type ListSentLikesRow struct {
	Persona Persona
	Matched bool
}

// その日の Like 配分の履歴。Match した相手も一覧に残し、画面が MATCH バッジを
// 出せるようフラグを立てる。
//
// sqlc.embed で Persona を丸ごと受け取るのは、ハンドラが列を1つずつ写さずに
// 済ませるため。写し忘れた列は画面から黙って消える。
func (q *Queries) ListSentLikes(ctx context.Context, personaID uuid.UUID) ([]ListSentLikesRow, error) {
	rows, err := q.db.Query(ctx, listSentLikes, personaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSentLikesRow{}
	for rows.Next() {
		var i ListSentLikesRow
		if err := rows.Scan(
			&i.Persona.ID,
			&i.Persona.ParticipantID,
			&i.Persona.Age,
			&i.Persona.Gender,
			&i.Persona.HeightCm,
			&i.Persona.Education,
			&i.Persona.Occupation,
			&i.Persona.AnnualIncome,
			&i.Persona.Name,
			&i.Persona.Hobby,
			&i.Persona.Bio,
			&i.Persona.ExposureCount,
			&i.Persona.CreatedAt,
			&i.Persona.PhotoUpdatedAt,
			&i.Persona.ProfileRewardClaimed,
			&i.Persona.MatchRewardCount,
			&i.Persona.LikeBalance,
			&i.Persona.LikeRecoveryAnchorAt,
			&i.Matched,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
