// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_children.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMatchChild = `-- name: GetMatchChild :one
SELECT id, match_id, gender, height_cm, education, occupation, annual_income, created_at FROM match_children WHERE match_id = $1
`

func (q *Queries) GetMatchChild(ctx context.Context, matchID uuid.UUID) (MatchChild, error) {
	row := q.db.QueryRow(ctx, getMatchChild, matchID)
	var i MatchChild
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchForPersona = `-- name: GetMatchForPersona :one
SELECT
    m.id AS match_id,
    cp.id, cp.participant_id, cp.age, cp.gender, cp.height_cm, cp.education, cp.occupation, cp.annual_income, cp.name, cp.hobby, cp.bio, cp.exposure_count, cp.created_at, cp.photo_updated_at, cp.profile_reward_claimed, cp.match_reward_count, cp.like_balance, cp.like_recovery_anchor_at
FROM matches m
JOIN personas cp ON cp.id = CASE
    WHEN m.persona_low_id = $1 THEN m.persona_high_id
    ELSE m.persona_low_id
END
JOIN participants pa ON pa.id = cp.participant_id
WHERE m.id = $2
  AND (m.persona_low_id = $1 OR m.persona_high_id = $1)
  AND pa.game_date = $3
`

type GetMatchForPersonaParams struct {
	PersonaID uuid.UUID
	MatchID   uuid.UUID
	GameDate  time.Time
}

type GetMatchForPersonaRow struct {
	MatchID uuid.UUID
	Persona Persona
}

// 指定 Match を、それが「自分が含まれる当日の Match」である場合だけ返す。
// 相手 Persona も一緒に取るので、Match 詳細はこれ1本で組み立てられる。
//
// 3つの確認をこの1本にまとめている:
//   - Match が存在する
//   - 自分がそのペアに含まれている（WHERE 節の OR）
//   - 当日有効である（相手 participant の game_date）
//
// 呼び出し側の persona_id は当日の participant から引いたものなので、
// 相手側の game_date を見れば両者が当日であることが決まる。
func (q *Queries) GetMatchForPersona(ctx context.Context, arg GetMatchForPersonaParams) (GetMatchForPersonaRow, error) {
	row := q.db.QueryRow(ctx, getMatchForPersona, arg.PersonaID, arg.MatchID, arg.GameDate)
	var i GetMatchForPersonaRow
	err := row.Scan(
		&i.MatchID,
		&i.Persona.ID,
		&i.Persona.ParticipantID,
		&i.Persona.Age,
		&i.Persona.Gender,
		&i.Persona.HeightCm,
		&i.Persona.Education,
		&i.Persona.Occupation,
		&i.Persona.AnnualIncome,
		&i.Persona.Name,
		&i.Persona.Hobby,
		&i.Persona.Bio,
		&i.Persona.ExposureCount,
		&i.Persona.CreatedAt,
		&i.Persona.PhotoUpdatedAt,
		&i.Persona.ProfileRewardClaimed,
		&i.Persona.MatchRewardCount,
		&i.Persona.LikeBalance,
		&i.Persona.LikeRecoveryAnchorAt,
	)
	return i, err
}

const insertMatchChild = `-- name: InsertMatchChild :one
INSERT INTO match_children (
    id, match_id, gender, height_cm, education, occupation, annual_income
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (match_id)
DO UPDATE SET match_id = match_children.match_id
RETURNING id, match_id, gender, height_cm, education, occupation, annual_income, created_at
`

type InsertMatchChildParams struct {
	ID           uuid.UUID
	MatchID      uuid.UUID
	Gender       string
	HeightCm     int16
	Education    string
	Occupation   string
	AnnualIncome int32
}

// 冪等な子ガチャの保存。1 Match につき子は1人だけなので、同時実行で
// INSERT に負けた側には保存済みの行がそのまま返る。よって多重クリックでも
// 再送でも引き直しは起きず、全員が同じ子を見る。
//
// DO UPDATE を無意味な代入にしているのは、Persona / Match の生成と同じ理由。
// DO NOTHING にすると負けた側の RETURNING が空になり、呼び出し側が
// 読み直しの分岐を持たなければならなくなる。
func (q *Queries) InsertMatchChild(ctx context.Context, arg InsertMatchChildParams) (MatchChild, error) {
	row := q.db.QueryRow(ctx, insertMatchChild,
		arg.ID,
		arg.MatchID,
		arg.Gender,
		arg.HeightCm,
		arg.Education,
		arg.Occupation,
		arg.AnnualIncome,
	)
	var i MatchChild
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.CreatedAt,
	)
	return i, err
}
