// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMatches = `-- name: CountMatches :one
SELECT COUNT(*) FROM matches
WHERE persona_low_id = $1 OR persona_high_id = $1
`

func (q *Queries) CountMatches(ctx context.Context, personaID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMatches, personaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasMatchesSince = `-- name: HasMatchesSince :one
SELECT EXISTS (
    SELECT 1 FROM matches
    WHERE (persona_low_id = $1 OR persona_high_id = $1)
      AND created_at > COALESCE($2::timestamptz, 'epoch'::timestamptz)
) AS has_unseen
`

type HasMatchesSinceParams struct {
	PersonaID uuid.UUID
	Since     *time.Time
}

func (q *Queries) HasMatchesSince(ctx context.Context, arg HasMatchesSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMatchesSince, arg.PersonaID, arg.Since)
	var has_unseen bool
	err := row.Scan(&has_unseen)
	return has_unseen, err
}
