// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertMatch = `-- name: InsertMatch :one
INSERT INTO matches (id, persona_low_id, persona_high_id)
VALUES ($1, $2, $3)
ON CONFLICT (persona_low_id, persona_high_id) DO UPDATE
SET persona_low_id = matches.persona_low_id
RETURNING id
`

type InsertMatchParams struct {
	ID            uuid.UUID
	PersonaLowID  uuid.UUID
	PersonaHighID uuid.UUID
}

// 正規化済みペアに対する冪等な Match 生成。DO UPDATE を無意味な代入にすることで
// 既存行が返るため、リトライしてもエラーにならず同じ match id が得られる。
func (q *Queries) InsertMatch(ctx context.Context, arg InsertMatchParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertMatch, arg.ID, arg.PersonaLowID, arg.PersonaHighID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
