// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Like struct {
	ID            uuid.UUID
	FromPersonaID uuid.UUID
	ToPersonaID   uuid.UUID
	CreatedAt     time.Time
}

type Match struct {
	ID            uuid.UUID
	PersonaLowID  uuid.UUID
	PersonaHighID uuid.UUID
	CreatedAt     time.Time
}

type Participant struct {
	ID                uuid.UUID
	CookieToken       uuid.UUID
	GameDate          time.Time
	CsrfToken         string
	LikesLastSeenAt   *time.Time
	MatchesLastSeenAt *time.Time
	CreatedAt         time.Time
}

type Pass struct {
	ID            uuid.UUID
	FromPersonaID uuid.UUID
	ToPersonaID   uuid.UUID
	PassCount     int16
	LastPassedAt  time.Time
}

type Persona struct {
	ID                   uuid.UUID
	ParticipantID        uuid.UUID
	Age                  int16
	Gender               string
	HeightCm             int16
	Education            string
	Occupation           string
	AnnualIncome         int32
	Name                 *string
	Hobby                *string
	Bio                  *string
	ExposureCount        int32
	CreatedAt            time.Time
	PhotoUpdatedAt       *time.Time
	ProfileRewardClaimed bool
	MatchRewardCount     int16
	LikeBalance          int16
	TimeRecoveryCount    int16
	LikeRecoveryAnchorAt *time.Time
}
