// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: participants.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteParticipantsBefore = `-- name: DeleteParticipantsBefore :execrows
DELETE FROM participants WHERE game_date < $1
`

func (q *Queries) DeleteParticipantsBefore(ctx context.Context, gameDate time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteParticipantsBefore, gameDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, cookie_token, game_date, csrf_token, likes_last_seen_at, matches_last_seen_at, created_at FROM participants
WHERE cookie_token = $1 AND game_date = $2
`

type GetParticipantParams struct {
	CookieToken uuid.UUID
	GameDate    time.Time
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.CookieToken, arg.GameDate)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.CookieToken,
		&i.GameDate,
		&i.CsrfToken,
		&i.LikesLastSeenAt,
		&i.MatchesLastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByCookieAndCSRF = `-- name: GetParticipantByCookieAndCSRF :one
SELECT id, cookie_token, game_date, csrf_token, likes_last_seen_at, matches_last_seen_at, created_at FROM participants
WHERE cookie_token = $1 AND csrf_token = $2
`

type GetParticipantByCookieAndCSRFParams struct {
	CookieToken uuid.UUID
	CsrfToken   string
}

func (q *Queries) GetParticipantByCookieAndCSRF(ctx context.Context, arg GetParticipantByCookieAndCSRFParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByCookieAndCSRF, arg.CookieToken, arg.CsrfToken)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.CookieToken,
		&i.GameDate,
		&i.CsrfToken,
		&i.LikesLastSeenAt,
		&i.MatchesLastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const markLikesSeen = `-- name: MarkLikesSeen :exec
UPDATE participants SET likes_last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) MarkLikesSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markLikesSeen, id)
	return err
}

const markMatchesSeen = `-- name: MarkMatchesSeen :exec
UPDATE participants SET matches_last_seen_at = NOW() WHERE id = $1
`

func (q *Queries) MarkMatchesSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMatchesSeen, id)
	return err
}

const upsertParticipant = `-- name: UpsertParticipant :one
INSERT INTO participants (id, cookie_token, game_date, csrf_token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cookie_token, game_date)
DO UPDATE SET cookie_token = participants.cookie_token
RETURNING id, cookie_token, game_date, csrf_token, likes_last_seen_at, matches_last_seen_at, created_at
`

type UpsertParticipantParams struct {
	ID          uuid.UUID
	CookieToken uuid.UUID
	GameDate    time.Time
	CsrfToken   string
}

// 競合に強い「当日の Participant を保証する」処理。DO UPDATE を無意味な代入に
// しておくと、同時実行で INSERT に負けた側でも既存行が RETURNING で返る。
func (q *Queries) UpsertParticipant(ctx context.Context, arg UpsertParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, upsertParticipant,
		arg.ID,
		arg.CookieToken,
		arg.GameDate,
		arg.CsrfToken,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.CookieToken,
		&i.GameDate,
		&i.CsrfToken,
		&i.LikesLastSeenAt,
		&i.MatchesLastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
