// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getPassCount = `-- name: GetPassCount :one
SELECT pass_count FROM passes
WHERE from_persona_id = $1 AND to_persona_id = $2
`

type GetPassCountParams struct {
	FromPersonaID uuid.UUID
	ToPersonaID   uuid.UUID
}

func (q *Queries) GetPassCount(ctx context.Context, arg GetPassCountParams) (int16, error) {
	row := q.db.QueryRow(ctx, getPassCount, arg.FromPersonaID, arg.ToPersonaID)
	var pass_count int16
	err := row.Scan(&pass_count)
	return pass_count, err
}

const upsertPass = `-- name: UpsertPass :one
INSERT INTO passes (id, from_persona_id, to_persona_id)
VALUES ($1, $2, $3)
ON CONFLICT (from_persona_id, to_persona_id) DO UPDATE
SET pass_count = passes.pass_count + 1,
    last_passed_at = NOW()
RETURNING pass_count
`

type UpsertPassParams struct {
	ID            uuid.UUID
	FromPersonaID uuid.UUID
	ToPersonaID   uuid.UUID
}

// 1回目は INSERT、2回目以降は加算。回数に上限は無い。Pass を何度受けても
// 相手が候補から消えることはなく、再表示までの間隔はフロントエンドの
// クールダウンだけが持つ。
func (q *Queries) UpsertPass(ctx context.Context, arg UpsertPassParams) (int16, error) {
	row := q.db.QueryRow(ctx, upsertPass, arg.ID, arg.FromPersonaID, arg.ToPersonaID)
	var pass_count int16
	err := row.Scan(&pass_count)
	return pass_count, err
}
