// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personas.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimMatchReward = `-- name: ClaimMatchReward :one
UPDATE personas
SET bonus_likes = bonus_likes + $1,
    match_reward_count = match_reward_count + 1
WHERE id = $2
RETURNING bonus_likes
`

type ClaimMatchRewardParams struct {
	Amount int16
	ID     uuid.UUID
}

// Match 報酬の付与。回数は1日2回で打ち止めなので、上限判定を済ませた
// 呼び出し側だけがこれを実行する。amount が 0 でも回数は消費する。
//
// Like のトランザクションが lockPair でこの行を FOR UPDATE しているため、
// 同時 Like でも回数が2を超えることはない。
func (q *Queries) ClaimMatchReward(ctx context.Context, arg ClaimMatchRewardParams) (int16, error) {
	row := q.db.QueryRow(ctx, claimMatchReward, arg.Amount, arg.ID)
	var bonus_likes int16
	err := row.Scan(&bonus_likes)
	return bonus_likes, err
}

const claimProfileReward = `-- name: ClaimProfileReward :one
UPDATE personas
SET bonus_likes = bonus_likes + $1,
    profile_reward_claimed = TRUE
WHERE id = $2
RETURNING id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at, photo_updated_at, bonus_likes, profile_reward_claimed, match_reward_count
`

type ClaimProfileRewardParams struct {
	Amount int16
	ID     uuid.UUID
}

// プロフィール完成報酬の付与。amount は所持上限で切り詰めた「実際に増える数」で、
// 上限に達していて 0 のときも受け取り済みにする。仕様どおり溢れた分は失われ、
// 同じ日にもう一度もらえることはない。
//
// 呼び出し側は LockPersona でこの行を押さえてから、フラグを読んで amount を
// 決める。よってページ再読み込みや同じ PATCH の再送では二度目の付与が起きない。
func (q *Queries) ClaimProfileReward(ctx context.Context, arg ClaimProfileRewardParams) (Persona, error) {
	row := q.db.QueryRow(ctx, claimProfileReward, arg.Amount, arg.ID)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
		&i.PhotoUpdatedAt,
		&i.BonusLikes,
		&i.ProfileRewardClaimed,
		&i.MatchRewardCount,
	)
	return i, err
}

const clearPersonaPhoto = `-- name: ClearPersonaPhoto :exec
UPDATE personas SET photo_updated_at = NULL WHERE id = $1
`

func (q *Queries) ClearPersonaPhoto(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPersonaPhoto, id)
	return err
}

const getActivePersona = `-- name: GetActivePersona :one
SELECT p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at, p.bonus_likes, p.profile_reward_claimed, p.match_reward_count FROM personas p
JOIN participants pa ON pa.id = p.participant_id
WHERE p.id = $1 AND pa.game_date = $2
`

type GetActivePersonaParams struct {
	PersonaID uuid.UUID
	GameDate  time.Time
}

// Persona が操作対象として有効なのは、その Persona 自身のゲーム日のみ。
func (q *Queries) GetActivePersona(ctx context.Context, arg GetActivePersonaParams) (Persona, error) {
	row := q.db.QueryRow(ctx, getActivePersona, arg.PersonaID, arg.GameDate)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
		&i.PhotoUpdatedAt,
		&i.BonusLikes,
		&i.ProfileRewardClaimed,
		&i.MatchRewardCount,
	)
	return i, err
}

const getHomeState = `-- name: GetHomeState :one
SELECT
    p.id, p.participant_id, p.age, p.gender, p.height_cm, p.education, p.occupation, p.annual_income, p.name, p.hobby, p.bio, p.exposure_count, p.created_at, p.photo_updated_at, p.bonus_likes, p.profile_reward_claimed, p.match_reward_count,
    (SELECT COUNT(*) FROM likes l WHERE l.from_persona_id = p.id) AS likes_sent,
    (SELECT COUNT(*) FROM likes l WHERE l.to_persona_id = p.id) AS likes_received,
    (
        SELECT COUNT(*) FROM matches m
        WHERE m.persona_low_id = p.id OR m.persona_high_id = p.id
    ) AS match_count,
    EXISTS (
        SELECT 1 FROM likes l
        WHERE l.to_persona_id = p.id
          AND l.created_at > COALESCE($1::timestamptz, 'epoch'::timestamptz)
    ) AS has_unseen_likes,
    EXISTS (
        SELECT 1 FROM matches m
        WHERE (m.persona_low_id = p.id OR m.persona_high_id = p.id)
          AND m.created_at > COALESCE($2::timestamptz, 'epoch'::timestamptz)
    ) AS has_unseen_matches
FROM personas p
WHERE p.participant_id = $3
`

type GetHomeStateParams struct {
	LikesLastSeenAt   *time.Time
	MatchesLastSeenAt *time.Time
	ParticipantID     uuid.UUID
}

type GetHomeStateRow struct {
	Persona          Persona
	LikesSent        int64
	LikesReceived    int64
	MatchCount       int64
	HasUnseenLikes   bool
	HasUnseenMatches bool
}

// ホーム（マイページ）に必要な情報を1往復で取得する。
// 以前は Persona 取得と5つの集計で6回の往復をしていた。
func (q *Queries) GetHomeState(ctx context.Context, arg GetHomeStateParams) (GetHomeStateRow, error) {
	row := q.db.QueryRow(ctx, getHomeState, arg.LikesLastSeenAt, arg.MatchesLastSeenAt, arg.ParticipantID)
	var i GetHomeStateRow
	err := row.Scan(
		&i.Persona.ID,
		&i.Persona.ParticipantID,
		&i.Persona.Age,
		&i.Persona.Gender,
		&i.Persona.HeightCm,
		&i.Persona.Education,
		&i.Persona.Occupation,
		&i.Persona.AnnualIncome,
		&i.Persona.Name,
		&i.Persona.Hobby,
		&i.Persona.Bio,
		&i.Persona.ExposureCount,
		&i.Persona.CreatedAt,
		&i.Persona.PhotoUpdatedAt,
		&i.Persona.BonusLikes,
		&i.Persona.ProfileRewardClaimed,
		&i.Persona.MatchRewardCount,
		&i.LikesSent,
		&i.LikesReceived,
		&i.MatchCount,
		&i.HasUnseenLikes,
		&i.HasUnseenMatches,
	)
	return i, err
}

const getPersonaByID = `-- name: GetPersonaByID :one
SELECT id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at, photo_updated_at, bonus_likes, profile_reward_claimed, match_reward_count FROM personas WHERE id = $1
`

func (q *Queries) GetPersonaByID(ctx context.Context, id uuid.UUID) (Persona, error) {
	row := q.db.QueryRow(ctx, getPersonaByID, id)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
		&i.PhotoUpdatedAt,
		&i.BonusLikes,
		&i.ProfileRewardClaimed,
		&i.MatchRewardCount,
	)
	return i, err
}

const getPersonaByParticipant = `-- name: GetPersonaByParticipant :one
SELECT id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at, photo_updated_at, bonus_likes, profile_reward_claimed, match_reward_count FROM personas WHERE participant_id = $1
`

func (q *Queries) GetPersonaByParticipant(ctx context.Context, participantID uuid.UUID) (Persona, error) {
	row := q.db.QueryRow(ctx, getPersonaByParticipant, participantID)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
		&i.PhotoUpdatedAt,
		&i.BonusLikes,
		&i.ProfileRewardClaimed,
		&i.MatchRewardCount,
	)
	return i, err
}

const incrementExposure = `-- name: IncrementExposure :exec
UPDATE personas SET exposure_count = exposure_count + 1 WHERE id = $1
`

// exposure は「実際に評価されたプロフィール」を数える。よって Like か Pass が
// 成功した後だけ実行し、Discover でバッチを返したときには実行しない。
func (q *Queries) IncrementExposure(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementExposure, id)
	return err
}

const insertPersona = `-- name: InsertPersona :one
INSERT INTO personas (
    id, participant_id, age, gender, height_cm, education, occupation, annual_income
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (participant_id)
DO UPDATE SET participant_id = personas.participant_id
RETURNING id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at, photo_updated_at, bonus_likes, profile_reward_claimed, match_reward_count
`

type InsertPersonaParams struct {
	ID            uuid.UUID
	ParticipantID uuid.UUID
	Age           int16
	Gender        string
	HeightCm      int16
	Education     string
	Occupation    string
	AnnualIncome  int32
}

// 冪等な Persona 生成。1 Participant につき Persona は1つだけなので、
// 同時実行で負けた側には保存済みの行がそのまま返る。
func (q *Queries) InsertPersona(ctx context.Context, arg InsertPersonaParams) (Persona, error) {
	row := q.db.QueryRow(ctx, insertPersona,
		arg.ID,
		arg.ParticipantID,
		arg.Age,
		arg.Gender,
		arg.HeightCm,
		arg.Education,
		arg.Occupation,
		arg.AnnualIncome,
	)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
		&i.PhotoUpdatedAt,
		&i.BonusLikes,
		&i.ProfileRewardClaimed,
		&i.MatchRewardCount,
	)
	return i, err
}

const lockPersona = `-- name: LockPersona :one
SELECT id FROM personas WHERE id = $1 FOR UPDATE
`

// Like / Pass トランザクションを直列化する。呼び出し側は必ずペアを正規化した
// (low, high) の順でロックする。これにより Like 予算の正しさと相互Like検出の
// 確実性を同時に満たし、かつデッドロックが起きない。
func (q *Queries) LockPersona(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockPersona, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const setPersonaPhoto = `-- name: SetPersonaPhoto :one
UPDATE personas SET photo_updated_at = NOW() WHERE id = $1 RETURNING photo_updated_at
`

func (q *Queries) SetPersonaPhoto(ctx context.Context, id uuid.UUID) (*time.Time, error) {
	row := q.db.QueryRow(ctx, setPersonaPhoto, id)
	var photo_updated_at *time.Time
	err := row.Scan(&photo_updated_at)
	return photo_updated_at, err
}

const updatePersonaProfile = `-- name: UpdatePersonaProfile :one
UPDATE personas
SET name = $2, hobby = $3, bio = $4
WHERE id = $1
RETURNING id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at, photo_updated_at, bonus_likes, profile_reward_claimed, match_reward_count
`

type UpdatePersonaProfileParams struct {
	ID    uuid.UUID
	Name  *string
	Hobby *string
	Bio   *string
}

func (q *Queries) UpdatePersonaProfile(ctx context.Context, arg UpdatePersonaProfileParams) (Persona, error) {
	row := q.db.QueryRow(ctx, updatePersonaProfile,
		arg.ID,
		arg.Name,
		arg.Hobby,
		arg.Bio,
	)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
		&i.PhotoUpdatedAt,
		&i.BonusLikes,
		&i.ProfileRewardClaimed,
		&i.MatchRewardCount,
	)
	return i, err
}
