// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personas.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getPersonaByID = `-- name: GetPersonaByID :one
SELECT id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at FROM personas WHERE id = $1
`

func (q *Queries) GetPersonaByID(ctx context.Context, id uuid.UUID) (Persona, error) {
	row := q.db.QueryRow(ctx, getPersonaByID, id)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
	)
	return i, err
}

const getPersonaByParticipant = `-- name: GetPersonaByParticipant :one
SELECT id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at FROM personas WHERE participant_id = $1
`

func (q *Queries) GetPersonaByParticipant(ctx context.Context, participantID uuid.UUID) (Persona, error) {
	row := q.db.QueryRow(ctx, getPersonaByParticipant, participantID)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertPersona = `-- name: InsertPersona :one
INSERT INTO personas (
    id, participant_id, age, gender, height_cm, education, occupation, annual_income
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (participant_id)
DO UPDATE SET participant_id = personas.participant_id
RETURNING id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at
`

type InsertPersonaParams struct {
	ID            uuid.UUID
	ParticipantID uuid.UUID
	Age           int16
	Gender        string
	HeightCm      int16
	Education     string
	Occupation    string
	AnnualIncome  int32
}

// Idempotent persona generation: a participant may only ever have one persona,
// so a losing concurrent request gets the already-stored row back.
func (q *Queries) InsertPersona(ctx context.Context, arg InsertPersonaParams) (Persona, error) {
	row := q.db.QueryRow(ctx, insertPersona,
		arg.ID,
		arg.ParticipantID,
		arg.Age,
		arg.Gender,
		arg.HeightCm,
		arg.Education,
		arg.Occupation,
		arg.AnnualIncome,
	)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
	)
	return i, err
}

const updatePersonaProfile = `-- name: UpdatePersonaProfile :one
UPDATE personas
SET name = $2, hobby = $3, bio = $4
WHERE id = $1
RETURNING id, participant_id, age, gender, height_cm, education, occupation, annual_income, name, hobby, bio, exposure_count, created_at
`

type UpdatePersonaProfileParams struct {
	ID    uuid.UUID
	Name  *string
	Hobby *string
	Bio   *string
}

func (q *Queries) UpdatePersonaProfile(ctx context.Context, arg UpdatePersonaProfileParams) (Persona, error) {
	row := q.db.QueryRow(ctx, updatePersonaProfile,
		arg.ID,
		arg.Name,
		arg.Hobby,
		arg.Bio,
	)
	var i Persona
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Age,
		&i.Gender,
		&i.HeightCm,
		&i.Education,
		&i.Occupation,
		&i.AnnualIncome,
		&i.Name,
		&i.Hobby,
		&i.Bio,
		&i.ExposureCount,
		&i.CreatedAt,
	)
	return i, err
}
